export const REQUEST_USER_DATA = "REQUEST_USER_DATA";
export const REQUEST_USER_DATA_SUCCESS = "REQUEST_USER_DATA_SUCCESS";
export const REQUEST_USER_DATA_FAILED = "REQUEST_USER_DATA_FAILED";
export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_DATA_FAILED = "UPDATE_USER_FAILED";
export const ADD_USER_DATA = "ADD_USER_DATA";
export const ADD_USER_DATA_SUCCESS = 'ADD_USER_DATA_SUCCESS';
export const ADD_USER_DATA_FAILED = 'ADD_USER_DATA_FAILED';
export const DELETE_USER_DATA = "DELETE_USER_DATA";
export const DELETE_USER_DATA_SUCCESS = "DELETE_USER_DATA_SUCCESS";
export const DELETE_USER_DATA_FAILED = "DELETE_USER_DATA_FAILED";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILED = "GET_USER_DATA_FAILED";

